// <auto-generated />
using System;
using Financial_management_system_in_educational_institutions_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Financial_management_system_in_educational_institutions_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250423110409_AddTblKomuna")]
    partial class AddTblKomuna
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Financial_management_system_in_educational_institutions_API.Models.Account", b =>
                {
                    b.Property<int>("accId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("accId"));

                    b.Property<string>("organisationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("twoFAcode")
                        .HasColumnType("int");

                    b.Property<DateTime>("twoFAtime")
                        .HasColumnType("datetime2");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("accId");

                    b.ToTable("tblAccounts");

                    b.HasData(
                        new
                        {
                            accId = 1,
                            organisationName = "Rilindja",
                            passwordHash = "324refds32q",
                            role = "kompani",
                            salt = "fdszx",
                            twoFAcode = 491593,
                            twoFAtime = new DateTime(2025, 4, 23, 13, 4, 9, 395, DateTimeKind.Local).AddTicks(9982),
                            username = "kompania1"
                        },
                        new
                        {
                            accId = 2,
                            organisationName = "Hasan Prishtina",
                            passwordHash = "vdsv2wqc2ws2",
                            role = "universitet",
                            salt = "adsyx",
                            twoFAcode = 154923,
                            twoFAtime = new DateTime(2025, 4, 23, 13, 4, 9, 396, DateTimeKind.Local).AddTicks(49),
                            username = "kompania1"
                        });
                });

            modelBuilder.Entity("Financial_management_system_in_educational_institutions_API.Models.Komuna", b =>
                {
                    b.Property<int>("komunaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("komunaId"));

                    b.Property<int>("accId")
                        .HasColumnType("int");

                    b.Property<decimal>("buxhetiAktual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ditaNdarjesAuto")
                        .HasColumnType("bit");

                    b.Property<int>("nrPopullsis")
                        .HasColumnType("int");

                    b.Property<string>("qyteti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("komunaId");

                    b.HasIndex("accId");

                    b.ToTable("tblKomuna", (string)null);
                });

            modelBuilder.Entity("Financial_management_system_in_educational_institutions_API.Models.Person", b =>
                {
                    b.Property<int>("numriPersonal")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataLindjes")
                        .HasColumnType("datetime2");

                    b.Property<string>("emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gjinia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mbiemri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nacionaliteti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qyteti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shteti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("numriPersonal");

                    b.ToTable("tblPersons");
                });

            modelBuilder.Entity("Financial_management_system_in_educational_institutions_API.Models.Shkolla", b =>
                {
                    b.Property<int>("shkollaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shkollaId"));

                    b.Property<int>("accId")
                        .HasColumnType("int");

                    b.Property<bool>("autoNdarja")
                        .HasColumnType("bit");

                    b.Property<decimal>("buxhetiAktual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("drejtori")
                        .HasColumnType("int");

                    b.Property<string>("emriShkolles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lokacioni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nrNxenesve")
                        .HasColumnType("int");

                    b.HasKey("shkollaId");

                    b.HasIndex("accId");

                    b.HasIndex("drejtori");

                    b.ToTable("tblShkolla");
                });

            modelBuilder.Entity("Financial_management_system_in_educational_institutions_API.Models.Komuna", b =>
                {
                    b.HasOne("Financial_management_system_in_educational_institutions_API.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("accId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Financial_management_system_in_educational_institutions_API.Models.Shkolla", b =>
                {
                    b.HasOne("Financial_management_system_in_educational_institutions_API.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("accId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Financial_management_system_in_educational_institutions_API.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("drejtori")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
